# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish aplikace
      run: dotnet publish --configuration Release --no-build --output ./publish_output

    - name: Nahrání do Artifactů
      uses: actions/upload-artifact@v7
      with:
        name: OdectyMVC
        path: ./publish_output # Cesta ke složce, kterou jsme definovali v kroku 'Publish'
        if-no-files-found: error
